version: '3.7'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
  backend:
    image: ${REGISTRY_HOST}/taskflow_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3222:3222
    networks:
      - backend-network
      - frontend-network
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      # - ./backend/.env
      - /home/dev/utilities/envs/taskflow_backend.env
    restart: unless-stopped
  frontend:
    image: ${REGISTRY_HOST}/taskflow_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3001
    networks:
      - frontend-network
    depends_on:
      - backend
    restart: unless-stopped
networks:
  backend-network:
  frontend-network:

volumes:
  mongodb-data:
