import Header from '../../components/Header/Header'
import './globals.css'
import 'bootstrap-icons/font/bootstrap-icons.css';
import {useLocale} from 'next-intl';
import {notFound} from 'next/navigation';

export const metadata = {
  title: 'TaskFlow',
  description: 'Generated by create next app',
}

export default (function RootLayout({
  children, params
}: {
  children: React.ReactNode, params: any
}) {
  const locale = useLocale();
 
  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }
  return (
    <>
      <head>
        <link rel="preconnect" href="https://use.typekit.net" />
        <link rel="stylesheet" href="https://use.typekit.net/fqs3vet.css"/>
      </head>
      <html lang={locale} className="scroll-smooth">
        <body className="bg-white text-dark text">
          <Header locale={locale} />
          {children}
        </body>
      </html>
    </>
  )
})